# Generated by Django 5.0.14 on 2025-09-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugstab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugstab', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alfabeth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
                ('bugstab', models.ManyToManyField(related_name='item', to='tysk.bugstab')),
            ],
        ),
    ]
