# Generated by Django 5.0.14 on 2025-09-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bogstav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogstav', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alfabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ord', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField(blank=True)),
                ('bogstav', models.ManyToManyField(related_name='item', to='dansk.bogstav')),
            ],
        ),
    ]
